site_name: Pythentur Docs
plugins:
  - search

theme:
  name: material
  palette:
    primary: cyan

repo_name: 'kmaasrud/pythentur'
repo_url: 'https://github.com/kmaasrud/pythentur'

markdown_extensions:
  - admonition
  - toc

pages:
  - 'Introduction': 'index.md'
  - 'User guide':
    - 'Getting to know the object types': 'userguide/getting-to-know.md'
    - 'Usage': 'userguide/usage.md'